#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "mongo-express"
name = "Mongo Express"
description.en = "An admin server for Mongo and optionally a Mongo database"
description.fr = "Un serveur d'administration pour Mongo ainsi qu'optionnellement une base Mongo"

version = "1.0~ynh4"

maintainers = ["Gerard Collin"]

[upstream]
license = "MIT"
code = "https://github.com/mongo-express/mongo-express"
cpe = "cpe:2.3:a:mongo-express_project:mongo-express"

[integration]
yunohost = ">= 11.0.0"
# FIXME: Test other architectures
architectures = ["amd64"]
multi_instance = false
ldap = "not_relevant"
sso = "not_relevant"
disk = "50M" # FIXME: replace with an **estimate** minimum disk requirement. e.g. 20M, 400M, 1G, ...
ram.build = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...
ram.runtime = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/mongo"

    [install.init_main_permission]
    type = "group"
    default = false

    [install.mongo_version]
    ask.en = "Select the major version of Mongo to install or 'None' if already installed"
    ask.fr = "Choisissez la version de Mongo a installer ou 'None' si Mongo est déjà installé"
    type = "string"
    choices = ["None", "4.4", "5.0", "6.0"]
    default = "6.0"

[resources]
    [resources.sources.main]
    url = "https://github.com/mongo-express/mongo-express/archive/refs/tags/v1.0.0.tar.gz"
    sha256 = "584bed4033f4b8f2f16824ec1eabfb3919aa04dfef72673a4e5ca8f4ef9f3b92"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset = ".*.tar.gz"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 8096
